version: '3.8'

services:
  back-end:
    build:
      context: ./back-end
      target: dev
    environment:
      DATABASE_URL: postgres://postgres:password@database:5432/postgres
      TEST_DATABASE_URL: postgres://postgres:password@test-database:5432/postgres
    ports:
      - 4000:4000
    volumes:
      - ./back-end/src:/app/src
      - /app/node_modules
    depends_on:
      - database

  front-end:
    image: front-end
    build:
      context: ./front-end
      target: dev
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./front-end:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - back-end

  database:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - database-content:/var/lib/postgresql/data
    expose:
      - 5432

  test-database:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_PASSWORD: password
    expose:
      - 5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081

volumes:
  database-content:
