name: build-test

on: push

jobs:
  back-end:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Check DNS resolution for test-database
        run: ping test-database
      - name: Run Prisma migrations for back-end
        run: docker-compose -f docker-compose.ci.back-end.yml run --rm back-end npx prisma migrate dev
      - name: Build and test back-end
        run: docker compose -f docker-compose.ci.back-end.yml up --build --exit-code-from back-end

  front-end:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build and test front-end
        run: docker compose -f docker-compose.ci.front-end.yml up --build --exit-code-from front-end
